Add functional tests to rpe push script

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -37,6 +37,21 @@ if [ $? -ne 0 ] ; then
 fi
 
 echo ""
+echo -e "${YELLOW}Running functional tests...${NOCOLOR}"
+echo ""
+
+cd ../Functional/Tests
+
+dotnet test
+
+if [ $? -ne 0 ] ; then
+    echo ""
+	echo -e "${RED}One or more unit tests failed. Please correct them before uploading changes${NOCOLOR}"
+	echo ""
+	exit 1
+fi
+
+echo ""
 echo -e "${GREEN}Pre push completed. Everything is OK${NOCOLOR}"
 echo ""
 
